language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t kkkamatchi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kkkamatchi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker_test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-222215666682"
  bucket_path: "docker_test"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key: "$AWS_SCode"
